# Generated by Django 4.2.5 on 2023-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_itemboleta_boleta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemboleta',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
